### ISSUE TITLE
zflecs: Questions and discussion on direction of the library

### ISSUE THREAD

**Issue by foxnne** [michal-z/zig-gamedev#261]
Hello!

First off, nice work on `zflecs`, as well as the rest of `zig-gamedev`, I've enjoyed using it very much on my projects.

I'm currently looking to update my [second project](https://github.com/foxnne/aftersun) which I haven't touched in a bit, and begin migrating over to `zflecs` from my own fork, [zig-flecs](https://github.com/foxnne/zig-flecs).

The reason I'm creating this issue is just to have a place to discuss the library and any missing features that may be a PR from contributors. I would be happy to help with the project if I can.

## Relationships

One of the first things I've come across when looking at the library that is different than mine, is that there seems to be no way to easily create and update pairs to the full extent that they can be with flecs. It seems currently `add_pair` only accepts (2) *entities*, whereas pairs can contain data just like components. If my memory serves, `flecs.h` has `ecs_pair_first` and `ecs_pair_second`, which will to access the data attached to a pair.  `make_pair` is exposed, which returns an id from two entities, but this does not seem to solve all use cases. In `zig-flecs`, I fell into using `anytype` for most functions that can accept either a *type, enum, union or id* and handled that accordingly through asserts, but I get the feeling you do not want to go that route with zflecs. If I understand correctly, you can get around supporting any of these by requiring that the user use `id()` or  `pair()` to get the id which is an entity as well, but does not solve setting/getting the attached data of the pair. I suppose then that `ecs_remove_id()` is then the only way to handle removing a pair.

Example from my project where `Request` is a tag and `Movement` contains data:
```ts
// ! When setting pairs, the intended data type attached must either be matched with a tag, or first in the pair of components.
flecs.ecs_set_pair_second(world, entity, components.Request, &components.Movement{ .start = tiles[i], .end = end_tile });
```

I guess my question here is: Should I try to submit a PR for adding these data to the pairs and we keep everything else as-is? I just don't want to submit PR's that are the wrong direction. 

## Style

I haven't yet used a library from zig-gamedev that didn't seem to follow the Zig style suggestions, so I was just curious why you chose to go with the style `flecs` uses in it's C API? I don't really feel super strongly about it either way, but it does look a little odd in use mixing the different styles. I did the same when I made my binding but after using it in a larger project than simple examples, mixing in with other zig code, it does seem to affect readability. This especially looks a little confusing when in VSCode functions aren't colored as functions. I realize in this case `SYSTEM` is "replacing" a macro, but I feel like that information is secondary to readability.

Some examples:
<img width="602" alt="Screenshot 2023-04-05 at 12 55 46 AM" src="https://user-images.githubusercontent.com/49629865/229993446-609b86e9-82bb-491b-ab59-adcf66f30d44.png">
 - note that `SYSTEM` and `EcsOnUpdate`  in VSCode are colored like that of `Types`s and not a function and variable as they are.

<img width="602" alt="Screenshot 2023-04-05 at 12 56 52 AM" src="https://user-images.githubusercontent.com/49629865/229993701-abb69690-ab94-482c-8774-22cea2657503.png">

Rather than sticking with the `flecs` style, I would lean more toward "owning" the wrapper and migrating to the Zig style.

## General and Missing Items
"How do I accomplish this using zflecs?"

- Adding/replacing enum components using enum values:
```ts 
flecs.ecs_add_pair(world, entity, components.Direction.none, components.Movement);
flecs.ecs_add_pair(world, entity, components.Direction.east, components.Movement);
```

## Summary of Suggested Items

**Relations**
- [x] Add `setPairFirst` or `set_pair_first`#280
- [x] Add `setPairSecond` or `set_pair_second` #280

**Systems**
- [x] Revise `SYSTEM` to accept a `system_desc_t` rather than a `query_desc_t` and `iter_action_t`, as both of those can be set up more easily in a `system_desc_t` and passed along. #281 

**Style**
- [x] ~~Conform to Zig style (preferred)~~ *or* choose to stick with Flecs style

**General**
- [x]  Add missing `override` functions #285
- [x]  Add missing `prefab` functions #285

This is all I have right now but will add to this as I begin migrating.

Thanks!

**Comment by michal-z** [comment]
Thanks for this issue, this is exactly what I need to move forward. Please give me few days, I will resume work on `zflecs` and answer your questions very soon.

**Comment by foxnne** [comment]
Starting out I'm getting an error trying to build:

```
Build Summary: 8/13 steps succeeded; 1 failed (disable with -fno-summary)
run transitive failure
└─ run Aftersun transitive failure
   ├─ zig build-exe Aftersun Debug native 1 errors
   │  ├─ options cached
   │  ├─ options cached
   │  ├─ options cached
   │  ├─ options (reused)
   │  ├─ options (reused)
   │  ├─ zig build-lib zglfw Debug native success 65ms MaxRSS:35M
   │  ├─ zig build-lib zstbi Debug native success 14ms MaxRSS:26M
   │  ├─ zig build-lib zgui Debug native success 16ms MaxRSS:27M
   │  ├─ options (reused)
   │  ├─ zig build-lib zflecs Debug native success 17ms MaxRSS:26M
   │  └─ install /Users/foxnne/dev/proj/aftersun/assets// cached
   └─ install transitive failure
      ├─ zig build-exe Aftersun Debug native (+11 more reused dependencies)
      └─ install Aftersun transitive failure
         └─ zig build-exe Aftersun Debug native (+11 more reused dependencies)
src/deps/zig-gamedev/zflecs/src/zflecs.zig:73:5: error: dependency loop detected
pub const iter_action_t = *const fn (it: *iter_t) callconv(.C) void;
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    iter_t: src/deps/zig-gamedev/zflecs/src/zflecs.zig:472:27
    iter_next_action_t: src/deps/zig-gamedev/zflecs/src/zflecs.zig:82:48
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

I believe I saw you mention in an issue that this was a bug in the zig compiler? Though I'm not too sure why this doesn't pop up running `zig build test` on the zig-gamedev project.

**Comment by michal-z** [comment]
Do you use the latest compiler? I saw this error in an older version... I think..

**Comment by michal-z** [comment]
Should be fine. Will try to repro.

**Comment by foxnne** [comment]
Great, thanks! I'm going to continue adding to this issue as I go along, please let me know if there is any better format. I just wanted to be able to list off suggestions and pending your approval or opinion on what fits your vision for the library I would be happy to contribute.

**Comment by Hastur007** [comment]
I don't know if this will help you, but the following code compiled.

```
const std = @import("std");
const ecs = @import("zflecs");

const Position = struct {
    x: f32,
    y: f32,
};
const Velocity = struct {
    x: f32,
    y: f32,
};

fn move(it: *ecs.iter_t) callconv(.C) void {
    const p = ecs.field(it, Position, 1).?;
    const v = ecs.field(it, Velocity, 2).?;

    const type_str = ecs.table_str(it.world, it.table).?;
    std.debug.print("Move entities with [{s}]\n", .{type_str});
    defer ecs.os.free(type_str);

    for (0..it.count()) |i| {
        p[i].x += v[i].x;
        p[i].y += v[i].y;
    }
}

pub fn sample() void {
    _ = std.mem.zeroes(ecs.iter_t); // Compilation error if commented out(Add `pub` for the call).

    var world = ecs.init();
    defer _ = ecs.fini(world);

    ecs.COMPONENT(world, Position);
    ecs.COMPONENT(world, Velocity);

    const e0 = ecs.new_entity(world, "Bob");
    _ = ecs.set(world, e0, Position, .{ .x = 0, .y = 0 });
    _ = ecs.set(world, e0, Velocity, .{ .x = 1, .y = 4 });

    ecs.SYSTEM(world, "move system", move, ecs.EcsOnUpdate, .{
        .filter = .{
            .terms = [_]ecs.term_t{
                .{ .id = ecs.id(Position) },
                .{ .id = ecs.id(Velocity) },
            } ++ ecs.array(ecs.term_t, ecs.TERM_DESC_CACHE_SIZE - 2),
        },
    });

    _ = ecs.progress(world, 0);

    const p = ecs.get(world, e0, Position).?;
    std.debug.print("Position = ({d} {d})\n", .{ p.x, p.y });
}

```

**Comment by michal-z** [comment]
@foxnne 

Regarding `ecs.SYSTEM()` -- when passing `system_desc_t` user will have to write below code by himself, right?

```zig
    var entity_desc = entity_desc_t{};
    entity_desc.id = new_id(world);
    entity_desc.name = name;
    entity_desc.add[0] = if (phase != 0) pair(EcsDependsOn, phase) else 0;
    entity_desc.add[1] = phase;

    var system_desc = system_desc_t{};
    system_desc.entity = entity_init(world, &entity_desc);
    system_desc.query = query_desc;
    system_desc.callback = callback;
    ...
```

The idea was to make it easier for the user and create an entity for the system "behind the scene".

**Comment by foxnne** [comment]
I believe there are some complexities with systems that your current `SYSTEM` doesn't allow, consider [this system](https://github.com/foxnne/aftersun/blob/edc074cb4b54edbdbd857da1545e4ea61c8ccc08/src/ecs/systems/movement_collision.zig#L16-L33). 

Here, we are in a larger project where systems are in their own files, with setup code included. I think this is naturally the organization that projects using flecs will be similar to, rather than having the setup code at the `ecs.SYSTEM()` call site.

Note that in this particular system, I'm using `system_desc.ctx` to pass in `group_by` query. This is currently not possible to do if using `ecs.SYSTEM` in its current state. 

If `ecs.SYSTEM` accepted a pre-created `system_desc_t`, you could still fill out the `system_desc.entity` field for the user based on the system name, like [this](https://github.com/foxnne/zig-flecs/blob/6115b21c93abcea76b12e5ec842c14000d1d0d7b/src/flecs.zig#L96-L105).

Maybe this isn't the way you want to go, but I'm not sure off the top of my head what all system features you will have to support with an `options` struct or something similar to fill in the `system_desc_t` if you don't let the user handle it.

The other option would be to keep what you currently have, and for more complex systems, the user has to handle everything and not use the `eco.SYSTEM` macro, but in my opinion it would feel a little strange to limit based on that.

And regarding style, I think that's fair. Like I said, I don't feel super strongly about it either way, its just a minor annoyance that `zflecs` code stylistically clashes with other surrounding zig code.

**Comment by foxnne** [comment]
@michal-z 

Another consideration, how would I accomplish the following with zflecs:
```ts
flecs.ecs_add_pair(world, entity, components.Direction.none, components.Movement);
```
or

```ts
flecs.ecs_add(world, entity, components.Direction.none);
```

Flecs supports using enums as components, and this is super handy for state-related systems. If the above were already called and I wanted to change direction, the following call would simply replace the previous "movement direction" value rather than having to remove a pair (checking if its added already) and then re-add a new one.

```ts
flecs.ecs_add_pair(world, entity, components.Direction.east, components.Movement);
```

**Comment by michal-z** [comment]
Thanks for the info, your experience using `flecs` is very valuable. You are probably right regarding `ecs.SYSTEM()`.

Btw, have you seen our tests https://github.com/michal-z/zig-gamedev/blob/main/libs/zflecs/src/tests.zig ?

Regarding the enums, we do:
```zig
_ = ecs.set(world, e0, Direction, .west);
```

I will be reading all your info in detail in the coming days and re-consider my initial choices.

**Comment by foxnne** [comment]
<img width="1392" alt="Screenshot 2023-04-19 at 12 18 19 PM" src="https://user-images.githubusercontent.com/49629865/233151544-88e8c4c5-708e-4b24-b1f8-bee41426780f.png">

Got my game back up and running using zflecs, most changes were simply names and syntax. I did have to add some missing things, and will likely PR those changes if you'd like. 

Also, if you'd like to use this project as a reference to see a slightly larger project using zflecs, feel free: [aftersun](https://github.com/foxnne/aftersun)
